#!/usr/bin/env bash
cubemx_img_name="stm32cubemx"


#====================================
# Docker command build arguments
bld_cmd="DOCKER_BUILDKIT=1 docker buildx build "
if [[ "$1" == "clean" ]]; then
    echo "Clean build....."
    # don't use the cache for the build, aka clean build
    bld_cmd+=" --no-cache"
fi
bld_cmd+=" -t ${cubemx_img_name} ."
#=====================================
echo "${bld_cmd}"
eval "${bld_cmd}"
