#!/usr/bin/env bash
cubemx_img_name="stm32cubemx"


start_location=$(realpath "$1")
echo "The container will start in ${start_location}"


pushd "${start_location}" || exit 1
    # make sure we've got a history file
    hst_file=".bash_history"

    if [[ ! -e "${hst_file}" ]]; then
        touch "${hst_file}"
    fi

    xhost +local:
    # shellcheck disable=SC2093
	run_cmd="docker run"
    run_cmd+=" --rm"
    run_cmd+=" --tty"
    run_cmd+=" --interactive"
    run_cmd+=" --env TERM=xterm-256color"
    run_cmd+=" --pid=host -e DISPLAY=${DISPLAY}"
    run_cmd+=" --network host"
    run_cmd+=" --hostname ${cubemx_img_name}"
    run_cmd+=" --volume /dev:/dev"
    run_cmd+=" --volume /opt:/tmp"
    run_cmd+=" --volume /home/${USER}/.ssh:/home/tiger/.ssh:ro"
    run_cmd+=" --volume /tmp/.X11-unix:/tmp/.X11-unix:ro"
    run_cmd+=" --volume /etc/timezone:/etc/timezone:ro"
    run_cmd+=" --volume /usr/share/zoneinfo/Europe/London:/etc/localtime:ro"
    run_cmd+=" --volume /media/${USER}:/media/tiger"
    run_cmd+=" --volume $(pwd):/home/tiger"
    run_cmd+=" ${cubemx_img_name}:latest"
    run_cmd+=" /bin/bash"
	eval "${run_cmd}"
popd || exit 1


